import "@/app/globals.css";
import Link from "next/link";
import DeployButton from "@/components/ui/deploy-button";
import { UserProvider } from "../context/provider";

export const metadata = {
  title: "Ship it quick ⚡️",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <UserProvider>
      <div className="max-w-xl mx-4 mt-8 lg:mx-auto">
        <nav className="">
          <div className="flex flex-row items-center">
            <div className="flex flex-1 gap-4">
              <Link className="hover:link" href="/dashboard">
                page
              </Link>
              <Link className="hover:link" href="/dashboard/settings">
                settings
              </Link>
            </div>
            <DeployButton />
          </div>
        </nav>

        <main className="my-10">{children}</main>
      </div>
    </UserProvider>
  );
}
