import "@/app/globals.css";
import { signOutAction } from "@/utils/auth-helpers/actions";
import { APPLICATION_NAME } from "@/config";
import { SubmitButton } from "@/components/ui/submit-button";
import Link from "next/link";

export const metadata = {
  title: "Ship it quick ⚡️",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="max-w-xl mx-4 mt-8 lg:mx-auto">
      <nav className="">
        <div className="flex flex-row items-center">
          <div className="flex flex-1 gap-4">
            <Link className="hover:link" href="/dashboard">
              Page
            </Link>
            <Link className="hover:link" href="/dashboard/settings">
              Settings
            </Link>
          </div>
          <button className="btn btn-warning mr-3">Deploy</button>
          {/* <form>
            <SubmitButton
              pendingText="Logging out..."
              formAction={signOutAction}
              className="btn"
            >
              Log out
            </SubmitButton>
          </form> */}
        </div>
      </nav>
      <main className="mt-10">{children}</main>
    </div>
  );
}
